version: "3.8"

services:
  backend:
    build: .
    container_name: backend-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      # Ensure Spring knows where Redis is running
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  redis:
    image: redis:7.2-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: